### ISSUE TITLE
Simd left shift alternative

### ISSUE THREAD

**Issue by stevenhoving** [KholdStare/qnd-integer-parsing-experiments#3]
To be honest, I could not let this go, I love these type of performance optimizations.
As you described in #2, you had troubles with the left shift. ~~If we would up the simd feature requirement to ssse3~~ we can use _mm_shuffle_epi8 together with a shuffle 'lookup' table and your there.

```
__m128i shift_bytes_left(__m128i a, int imm8)
{
    constexpr auto mask = static_cast<char>(-128);
    static const char shift_shuffle_lookup[32]{
        mask, mask, mask, mask,mask, mask, mask, mask,mask, mask, mask, mask,mask, mask, mask, mask,
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
    };

    const auto lookup_center = shift_shuffle_lookup + 16;
    const auto shuffle = _mm_lddqu_si128(reinterpret_cast<const __m128i*>(lookup_center - imm8));
    return _mm_shuffle_epi8(a, shuffle);
}
```

Update:
- on closer look, you are already using ssse3 features so this solution should be fine.
- according to your own benchmarks the proposed code is about 2-3x faster (on a i7-6700HQ).

**Comment by KholdStare** [comment]
Hey Steven! This is awesome. I was also fiddling around with trying to get a branchless left shift. I had some ideas but they ended up being a little slower for the best case and a little faster for the worst case compared to branching.

After trying this out, it's definitely a win. I'm going to make a commit with a CONTRIBUTORS file and use your implementation for the left shift. Now we're around ~1.25ns for numbers between 0 and 16 digits :+1: 

By the way, feel free to make pull requests with your ideas - that way your commit will be in there.
